# Spring Common Config
spring:
  profiles:
    active:
      - local
    group:
      local:
        - local
      prod:
        - prod
#  jpa:
#    hibernate:
#      # 기존 DB 맵핑시 에러 대응
#      use-new-id-generator-mappings: false
#      # 기존 DB 와 맵핑시 정책
#      ddl-auto: none
#      format_sql: true
#      show-sql: true
#      naming:
#        # name_strategy 설정
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    # JSON Snake Case (자동 변환)
    property-naming-strategy: SNAKE_CASE
    # File Upload Max Size
  servlet:
    multipart:
      max-file-size: 50MB

# Logging
#logging:
#  file:
#    name: logs/spring-web.log
#  level:
#    file: debug
#    org:
#      hibernate:
#        SQL: debug
#  pattern:
#    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# File Resource Path
upload-path:
  image:  ./resource/img
  txt:    ./resource/txt
  audio:  ./resource/audio
  etc:    ./resource/etc
