# Spring Common Config
spring:
  profiles:
    active:
      - local
    group:
      local:
        - local
      prod:
        - prod
  jpa:
    hibernate:
      # 기존 DB 맵핑시 에러 대응
      use-new-id-generator-mappings: false
      # 기존 DB 와 맵핑시 정책
      ddl-auto: none
      format_sql: true
      show-sql: true
  jackson:
    # JSON Snake Case (자동 변환)
    property-naming-strategy: SNAKE_CASE
    # File Upload Max Size
  servlet:
    multipart:
      max-file-size: 50MB

# Logging
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
        SQL: DEBUG
