server:
  port: 10004
  undertow:
    # WAS 는 undertow
    worker-threads: 4

# Local DB Config
spring:
  datasource:
    main:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/db_memo
      username: root
      password: 1234
    file:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/db_file
      username: root
      password: 1234

# Remote Host
remote_host: http://localhost:10004

# JWT Secret-key
jwt:
  secret-key: hello-spring-kkk