server:
  # Port 만사
  port: 10004
  undertow:
    # WAS 는 undertow
    worker-threads: 4

# Local DB Config
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db_memo
    username: root
    password: 1234
